spring:
  flyway:
    enabled: false

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:33061/follower
    username: user
    password: password

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 200

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
        format_sql: true
        default_batch_fetch_size: 100
        open-in-view: false
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: INFO

jwt:
  secret: ajenrvianeiuniuv3284373523knmvnv1$#%!42vj284hv
  access-token-valid-time-in-milliseconds: 60000000 # 600000 # 10 minutes
  refresh-token-valid-time-in-milliseconds: 3000000 # 604800000 # 1 week
