spring:
  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:33061/follower
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret: ajenrvianeiuniuv3284373523knmvnv1$#%!42vj284hv
  access-token-valid-time-in-milliseconds: 100000000 # 600000 # 10 minutes
  refresh-token-valid-time-in-milliseconds: 30000 # 604800000 # 1 week
